version: '3.9'

services:
  web:
    build: .
    env_file:
      - .env.prod
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./src/staticfiles:/app/staticfiles
      - ./src/media:/app/media

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/staticfiles:/app/staticfiles
      - ./src/media:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
